### ISSUE TITLE
Create Board 2

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#2]
Create the following board, no need to use global components or global styling yet. Use react state to store manually created data.

![image](https://ikehunter.com/wp-content/uploads/2023/09/Screenshot-2023-09-21-at-13.05.22.png)

**Comment by MichaelJK2143** [comment]
yo I'd be down to do this one

**Comment by IkeHunter** [comment]
Cool beans, I'll assign it

**Comment by DanielMelendezz** [comment]
I created a demo with this but my zipped folder is too large to upload here so here is a picture of what I did. With react front end and node.js backend that should work on any computer that has node.js installed.
![image](https://github.com/ufosc/Jukebox-Frontend/assets/108485934/b1a02a46-5392-4b70-a321-0295d439385b)
