### ISSUE TITLE
Create Queue List Component

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#3]
The component should be able to take in a list of songs and their info, and display the queue as a 1 column grid with each row displaying the song's information.

For testing purposes, this component can store static values for the songs as its own state.

**Comment by Ryan-slither** [comment]
I have been working on this one

**Comment by IkeHunter** [comment]
Ok, push up a new branch called "feature/queue-list" or something. Once you do that I'll merge it into main. I'm about to publish a new readme with better instructions on how to do that.

**Comment by Ryan-slither** [comment]
Done
