### ISSUE TITLE
Create Clock Component

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#4]
This component just displays the current time registered by the device. This will be in 12h time with a live seconds counter.

**Comment by jaken92** [comment]
Hello Ike! I would like to do this! Could you please assign me this issue ?

**Comment by IkeHunter** [comment]
Yep, I'll do that now!

**Comment by Mar1789** [comment]
Hey is this still available?

**Comment by IkeHunter** [comment]
@Mar1789 Yep, go for it!

**Comment by Mar1789** [comment]
Good Afternoon @IkeHunter . For the clock component, what page would you like the clock to be implemented and the desired location?

**Comment by IkeHunter** [comment]
@Mar1789 I think there's currently a Board1 component, you can put it in there for now. Once the wireframes for the boards are finished we can relocate it if needed

**Comment by Mar1789** [comment]
Okay! I already see that there is a digital component already made. Would you like it as a different visual style or do you want an actual clock?
<img width="753" alt="Screenshot 2024-02-06 at 2 59 34 PM" src="https://github.com/ufosc/Jukebox-Frontend/assets/116681148/d644e96c-2df6-43d2-aa7f-5fea709d1e6c">

**Comment by Mar1789** [comment]
@IkeHunter

**Comment by IkeHunter** [comment]
![Board 1 - Detailed 2](https://github.com/ufosc/Jukebox-Frontend/assets/23625299/6ac7f736-bc06-4c33-9376-1965e718bb24)
![Board 1 - Detailed](https://github.com/ufosc/Jukebox-Frontend/assets/23625299/8f8cf084-41ed-4791-9f3d-d76ff78c739c)
@Mar1789 Here's 2 wireframes with examples of the clock component.

It should be able to take the following props:
- [ ] primaryColor (default: #204246)
- [ ] secondaryColor (default: #285257)
- [ ] textColor (default: #ffffff)
- [ ] style ("standard", "flip") (default: "standard")
- [ ] format ("12-hour", "24-hour") (default: "12-hour")

You can "hard-code" the colors for now, I'll be building out the theme soon with a host of css variables and will change out the colors at that point.

The clock should be able to:
- [ ] Change it's main background color based on the `primaryColor` prop
- [ ] Change the color of the digit boxes based on the `secondaryColor` prop
- [ ] Change the digit color based on the `textColor` prop
- [ ] Change the time format based on the `format` prop
- [ ] Display the appropriate style of clock according to the `style` prop

Here's some other tasks:
- [ ] If the clock style is "flip", it should have a flip animation on digit change
- [ ] The colon should blink every second (not sure if we should have a quick fade or not, you can try using the `transition` css property to give it a fade if you want to try it out)
- [ ] Make sure it changes the digits based on the current time

Here's the styling of the digits that Figma generated (you can use it as a starting point, but it may need to be adjusted):
```css
.clock-digit {
  color: #FFF;
  font-family: Termina;
  font-size: 54px;
  font-style: normal;
  font-weight: 700;
  line-height: normal;
  letter-spacing: -0.54px;
}
```

**Comment by Mar1789** [comment]
@IkeHunter Hey so I started working on the clock component and copy and pasted the CSS styling that you provided. I also was able to make the colon have a fade-like visual. 
<img width="484" alt="Screenshot 2024-02-07 at 6 21 30 PM" src="https://github.com/ufosc/Jukebox-Frontend/assets/116681148/be98758c-4044-479d-92dd-82b978584760">

For clarification, do you want a function that changes between the two wireframes you displayed or is it more like me choosing what design to copy. Finally, you mentioned that the clock should be able to change colors when you said it's fine to hard-code it. Should I just make a function for just the time format?
