### ISSUE TITLE
Update Top Navigation Bar Component

### ISSUE THREAD

**Issue by JonathanHooth** [ufosc/Jukebox-Frontend#49]
Top Navigation Bar component's CSS styling should be modified to reflect the current style shown in the prototype shown in the figma.

Main Goal:
- [ ] Update top navigation bar to match current theming.

**Comment by raglandconnor** [comment]
Hey, I'd like to work on this.

**Comment by raglandconnor** [comment]
@JonathanHooth Where can I access the figma?

**Comment by IkeHunter** [comment]
@raglandconnor what's your ufl email? I can send an invite

**Comment by raglandconnor** [comment]
@IkeHunter I sent you an email with my ufl email

**Comment by IkeHunter** [comment]
@raglandconnor The top bar has updated slightly, there's now a group dropdown instead of a search bar
