### ISSUE TITLE
Build out Dashboard from prototype

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#50]
Wireframes:
![Home-dark](https://github.com/user-attachments/assets/eb04b1cf-71e5-45f2-b2cc-6b0ffcb3094c)
![Home](https://github.com/user-attachments/assets/4be3a3df-9caf-48c2-a4f8-4c407a1dc126)

**Comment by JonathanHooth** [comment]
I can handle this

**Comment by IkeHunter** [comment]
@JonathanHooth We need to have a default disc for when spotify is not connected, maybe for now we can just optionally render the song poster image (and remove it if there's no songs loaded)?

**Comment by JonathanHooth** [comment]
@IkeHunter I have changed the code to have it render the default song poster image when there is no song loaded.
