### ISSUE TITLE
Update Side Bar Component

### ISSUE THREAD

**Issue by JonathanHooth** [ufosc/Jukebox-Frontend#51]
Redo the CSS styling of the Side Bar Component to match the theming shown in the wireframes in the Figma. Make sure that all the functionality is present as shown in the wireframes.

Goal:
- [ ] Update Side Bar component to match current theming
- [ ] Add drop down menus for the Music, Jam Session, and Members section

**Comment by destingollamudi** [comment]
Hey new to frontend here, I can tackle this issue

**Comment by JonathanHooth** [comment]
Sounds good

**Comment by IkeHunter** [comment]
@destingollamudi Here's the wireframe:
![Sidebar](https://github.com/user-attachments/assets/3f2c8679-4d8c-4f56-b3d6-d920c115261e)

Sidebar with Dashboard light/dark mode:
![Admin Boards - Light](https://github.com/user-attachments/assets/4b58c3a1-a311-4818-90f2-fb99cf97ad50)
![Admin Boards - Dark](https://github.com/user-attachments/assets/804725d5-f7d5-4a4d-963e-13f4e88a662b)

**Comment by IkeHunter** [comment]
Updated sidebar:
![Sidebar](https://github.com/user-attachments/assets/16896a6f-02f0-4d98-ace4-89d77573e7a7)

**Comment by IkeHunter** [comment]
@QuickFingers2383 I'll leave this issue open for now, I can close it once you finish up with the svgs
