### ISSUE TITLE
Build out Board 3 page

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#57]
Mockups:
![Board 2 - Dark](https://github.com/user-attachments/assets/60bd6195-c824-4cae-922a-ffcec6ccd3ab)
![Board 2 - Light](https://github.com/user-attachments/assets/533a9a63-9406-40c6-b7d1-c26a54ef0a2a)

**Comment by BaisonBeast** [comment]
Hi, I would love to work on this issue. Can you please let me know does only the background needs to be changed or if the whole page has to be created?

**Comment by IkeHunter** [comment]
@BaisonBeast The right hand side, background, and clock components are already made (you can look at Board 1 to see how to implement them), you just need apply them to board3 and add the video component (the grey square - I forgot to label it). The goal with this component is a group/club could have a video playing on screen during their meeting, like subway surfers or something.
