### ISSUE TITLE
Create Now Listening Component

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#6]
This component will display the song that is currently playing. It will need to have a progress bar that changes depending on a numeric value. It will need to have controls that emit events. These events can just be console.log for testing purposes.

**Comment by Ryan-slither** [comment]
I will start working on this one

**Comment by s-trejo** [comment]
If this hasn't been completed yet may I take it?

**Comment by IkeHunter** [comment]
@s-trejo I don't think it's been finished yet, go for it!

**Comment by s-trejo** [comment]
@IKeHunter could you elaborate on "controls that emit events"?
