### ISSUE TITLE
Build Dashboard > Music pages

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#86]
## Task
Develop out the two pages in the "music" menu on the admin dashboard.

Includes:
- [ ] Tracks Queue page
- [ ] Search Tracks page

Use the existing color variables to allow light/dark mode.

### Music/Track queue
![Music - Dark](https://github.com/user-attachments/assets/f7b36a35-8efb-4bf9-93a8-c9829085f0be)
![Music - Light](https://github.com/user-attachments/assets/1c4dc2f0-561f-48ba-af54-8cde4a8587be)

### Music/Search
![Search Tracks - Dark](https://github.com/user-attachments/assets/5bfb0985-3c38-44de-a84b-8a304101ff27)
![Search Tracks - Light](https://github.com/user-attachments/assets/ff678a85-eb18-42e2-890a-20fd26793ee6)

**Comment by Ryan-slither** [comment]
I am working on this

**Comment by kluan01** [comment]
I am working on this w/ Ryan

**Comment by IkeHunter** [comment]
👌
