### ISSUE TITLE
Build out Login page

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#88]
## Task

- [ ] Build out the login page in the "Auth app" (`src/apps/auth` directory)

The form already exists, you just need to style it. Remember to use the global css variables to use light/dark mode features.

![Login Page - Light](https://github.com/user-attachments/assets/04f8673f-94d5-4929-aa1a-2e088ef7cac0)
![Login Page - Dark](https://github.com/user-attachments/assets/8ae1e36f-a3f2-4fec-a9d1-7f4708c3b284)

**Comment by Wasid786** [comment]
I would like to add this feature, can you assign this issue to me?

**Comment by rpa0309** [comment]
Can I start working on this issue?

**Comment by IkeHunter** [comment]
@rpa0309 Someone claimed this one during one of the OSC meetings, but I forgot to mark it here. There's a few other auth pages that need to be made, I'll be creating an issue shortly for a registration page and I can assign you to it

**Comment by rpa0309** [comment]
@IkeHunter Totally okay, thank you for the help! I would appreciate being assigned to that issue.
